feat: add new predicated for families rich text behind a feature flag
InseeFr/Bauhaus-Back-Office pull request #500
Opened 2024-02-08 12:45 UTC by EmmanuelDemey

2024-02-08 12:46 UTC, EmmanuelDemey commented
@JeromeMBourgeois @FBibonne afin de pouvoir merger des fonctionnalités sur la production sans les activer, j'ai initié un mécanisme de feature flipping. 

Pour info, les TU sont OK. Par contre, je n'ai pas encore eu le temps de vraiement tester, car j'ai un problème avec ma base GRAPHDB

2024-02-08 14:21 UTC, FBibonne requested changes
OK globalement mais il faudrait refactoriser un peu pour supprimer l'injection sur les champs dans FamiliesUtils et tester FamiliesUtils sans contexte Spring

2024-02-08 14:21 UTC, FBibonne commented on src/main/java/fr/insee/rmes/bauhaus_services/operations/families/FamiliesUtils.java
> +	boolean familiesRichTextNexStructure;
En profiter pour mettre en place l'injection des champs par constructeur pour la classe (NB RdfUtils.repositoryPublication RdfUtils.repositoryPublication sont inutiles)

2024-02-08 14:21 UTC, FBibonne commented on src/test/java/fr/insee/rmes/bauhaus_services/operations/families/FamiliesUtilsTest.java
> +@SpringBootTest({
Tester sans Spring boot (injection des mock par contructeur)

2024-02-08 14:21 UTC, FBibonne commented on src/main/java/fr/insee/rmes/bauhaus_services/operations/families/FamiliesUtils.java
> +			IRI iri1 = RdfUtils.addTripleStringMdToXhtml2(familyURI, DCTERMS.ABSTRACT, family.getAbstractLg1(), config.getLg1(), "resume", model, graph);
Factoriser dans une méthode l'appel à addTripleStringMdToXhtml2 + repoGestion.deleteObject et l'appeler deux fois (lg1 puis lg2)

2024-02-08 19:21 UTC, EmmanuelDemey commented
@FBibonne j'ai revu tous tes points

2024-02-09 05:48 UTC, FBibonne approved these changes

2024-02-09 12:55 UTC, merged