491-gérer les droits d'adminitration des codesLists
InseeFr/Bauhaus-Back-Office pull request #542
Opened 2024-03-06 16:04 UTC by GuyleneTandeauDeMarsac

Issue #491

2024-03-08 12:24 UTC, EmmanuelDemey requested changes

2024-03-08 12:24 UTC, EmmanuelDemey commented on src/main/java/fr/insee/rmes/bauhaus_services/code_list/CodeListServiceImpl.java
> +//				JSONObject codes = codesList.getJSONObject(CODES);
@GuyleneTandeauDeMarsac pourquoi ne pas wrapper tout ce code dans une condition comme celle suivante : 

```java
if(codesList.has(CODES)){
        JSONObject codes = codesList.getJSONObject(CODES);
	for (String key : codes.keySet()) {
				String codeIri = codes.getJSONObject(key).getString("iri");
				repoGestion.deleteObject(RdfUtils.toURI(codeIri), null);
	
        }
}
```

2024-03-11 12:46 UTC, GuyleneTandeauDeMarsac commented on src/main/java/fr/insee/rmes/bauhaus_services/code_list/CodeListServiceImpl.java
> +//				JSONObject codes = codesList.getJSONObject(CODES);
fait et modifié avec la proposition d'Emmanuel

2024-03-11 12:52 UTC, GuyleneTandeauDeMarsac commented on pom.xml
> -			<scope>provided</scope>
fait

2024-03-11 15:11 UTC, GuyleneTandeauDeMarsac commented on src/main/java/fr/insee/rmes/bauhaus_services/code_list/CodeListServiceImpl.java
> +//				JSONObject codes = codesList.getJSONObject(CODES);
fait

2024-03-11 16:11 UTC, FBibonne approved these changes

2024-03-11 16:12 UTC, merged