477 droits structures
InseeFr/Bauhaus-Back-Office pull request #559
Opened 2024-03-21 10:43 UTC by GuyleneTandeauDeMarsac

issue #477 
+ fix for codes lists

2024-03-22 10:56 UTC, FBibonne requested changes
Il ne faut surtout pas utiliser d'attribut dans CodeListQueries : cette classe doit rester sans état : il faut impérativement supprimer l'attribut CodeListQueries.params ligne 12 et le remplacer par des variables locales au sein des méthodes

2024-03-22 10:56 UTC, FBibonne commented on src/main/java/fr/insee/rmes/bauhaus_services/rdf_utils/RdfUtils.java
> +	public static IRI codesListIRI(String StringUri) {
Duplication de la méthode createIRI

2024-03-22 10:56 UTC, FBibonne commented on src/main/java/fr/insee/rmes/bauhaus_services/stamps/StampsRestrictionServiceImpl.java
> +	public boolean isStructureManagerWithStamp(IRI iri, String stamp) throws RmesException {
Déplacer dans StampAuthorizationChecker

2024-03-22 10:56 UTC, FBibonne commented on src/main/java/fr/insee/rmes/bauhaus_services/stamps/StampsRestrictionServiceImpl.java
> +	public boolean isComponentManagerWithStamp(IRI iri, String stamp) throws RmesException {
Déplacer dans StampAuthorizationChecker

2024-03-22 10:56 UTC, FBibonne commented on src/main/java/fr/insee/rmes/persistance/sparql_queries/structures/StructureQueries.java
> +	static Map<String, Object> params;
Surtout pas d'attribut params pour la classe : la classe  doit rester sans état

2024-03-25 10:09 UTC, GuyleneTandeauDeMarsac commented on src/main/java/fr/insee/rmes/bauhaus_services/StampAuthorizationChecker.java
> +	CodeListServiceImpl codeListService = new CodeListServiceImpl();
fait
et supprimé l'attribut CodeListQueries.params (idem dans StructureQueries) (d'ailleurs params est forcément null donc j'ai supprimé la condition if (params==null))

2024-03-29 09:21 UTC, FBibonne commented on src/main/java/fr/insee/rmes/bauhaus_services/StampAuthorizationChecker.java
> +	private String baseInternalUri;
On peut mettre l'attribut final je pense

2024-03-29 09:56 UTC, GuyleneTandeauDeMarsac commented on src/main/java/fr/insee/rmes/bauhaus_services/StampAuthorizationChecker.java
> +	private String baseInternalUri;
fait et testé avec un DELETE de liste de codes

2024-03-29 10:55 UTC, FBibonne approved these changes

2024-03-29 10:55 UTC, merged