575 patch distribution
InseeFr/Bauhaus-Back-Office pull request #590
Opened 2024-04-12 15:03 UTC by GuyleneTandeauDeMarsac

#575

2024-04-15 11:43 UTC, EmmanuelDemey requested changes

2024-04-15 11:43 UTC, EmmanuelDemey commented on src/main/java/fr/insee/rmes/bauhaus_services/distribution/DistributionService.java
> +    void PatchDistribution(String distributionId, PatchDistribution distribution) throws RmesException;
avec un petit p ?

2024-04-15 11:43 UTC, EmmanuelDemey commented on src/main/java/fr/insee/rmes/model/dataset/PatchDistribution.java
> +    private String taille;
taille ? Un terme anglais n'est pas préférable ?

2024-04-16 08:37 UTC, GuyleneTandeauDeMarsac commented on src/main/java/fr/insee/rmes/bauhaus_services/distribution/DistributionService.java
> +    void PatchDistribution(String distributionId, PatchDistribution distribution) throws RmesException;
oups :-) 
modified

2024-04-16 08:38 UTC, GuyleneTandeauDeMarsac commented on src/main/java/fr/insee/rmes/model/dataset/PatchDistribution.java
> +    private String taille;
j'avais adopté taille car c'était le terme déjà utilisé dans les end-points GET /distribution/{id} et GET /distribution
mais Florian a validé l'usage de l'anglais => modifié sur ces 2 end-points + le PATCH

2024-04-19 12:03 UTC, JeromeMBourgeois approved these changes

2024-04-19 12:04 UTC, EmmanuelDemey approved these changes

2024-04-19 12:04 UTC, merged