fix : change id generator for distribution and dataset
InseeFr/Bauhaus-Back-Office pull request #659
Opened 2024-06-20 15:23 UTC by HugoBouttes

no prefix and UUID version 4

#651

2024-06-25 09:18 UTC, EmmanuelDemey requested changes

2024-06-25 09:18 UTC, EmmanuelDemey commented on src/main/java/fr/insee/rmes/bauhaus_services/datasets/DatasetServiceImpl.java
> -        dataset.setId(IdGenerator.generateNextId(repoGestion.getResponseAsObject(DatasetQueries.lastDatasetId(getDatasetsGraph())), "jd"));
Est-il encore nécessaire de faire appel à la queries Sparql ?

2024-06-25 09:18 UTC, EmmanuelDemey commented on src/main/java/fr/insee/rmes/bauhaus_services/distribution/DistributionServiceImpl.java
> +        String idnewt = IdGenerator.generateNextId(repoGestion.getResponseAsObject(DistributionQueries.lastDatasetId(getDistributionGraph())));
Est-il encore nécessaire de faire appel à la queries Sparql ?

2024-06-25 09:18 UTC, EmmanuelDemey commented on src/main/java/fr/insee/rmes/utils/IdGenerator.java
> +    public static String generateNextId(JSONObject json) {
Le paramètre `json` n'est plus nécessaire.

2024-07-02 09:43 UTC, FBibonne requested changes
On pourrait ajouter un test sur generateNextId qui vérifie que l'UUID généré est bien de la version 4

2024-07-02 09:43 UTC, FBibonne commented on src/main/java/fr/insee/rmes/utils/IdGenerator.java
> +
- Supprimer les imports inutiles 
- Comme generateNextId n'est plus une simple transformation de donnée mais fait appel à un service tierce (randomUUID), on ne doit pas utiliser une méthode statique pour le rendre mais injecter une instance de IdGenerator dans les classes qui appellent la méthode generateNextId()

2024-07-02 09:43 UTC, FBibonne commented on src/main/java/fr/insee/rmes/bauhaus_services/distribution/DistributionServiceImpl.java
> -        distribution.setValidationState(ValidationStatus.UNPUBLISHED.toString());
Retirer la modification sur le statut de validation fait bien parti du scope de la PR ?

2024-07-02 09:43 UTC, FBibonne commented on src/test/java/fr/insee/rmes/bauhaus_services/datasets/DatasetServiceImplTest.java
> +                MockedStatic<IdGenerator> idGeneratorMock = Mockito.mockStatic(IdGenerator.class)
Utiliser l'injection d'un stub pour mocker l'usage de generateNextId()

2024-07-04 13:38 UTC, FBibonne approved these changes

2024-07-04 13:47 UTC, EmmanuelDemey approved these changes

2024-07-04 17:35 UTC, merged