657 refactoring controller : retourner des ResponseEntity d'objets
InseeFr/Bauhaus-Back-Office pull request #691
Opened 2024-07-09 14:58 UTC by GtanSndil

objets = de type CodeList, ou List<CodeList> ou autre

2024-07-10 07:02 UTC, EmmanuelDemey commented on src/main/java/fr/insee/rmes/bauhaus_services/code_list/CodeListServiceImpl.java
> -		result.put("items", items);
Personnellement je préfère garder un libellé générique. Comme cela, si un jour nous avons d'autres appels avec de la Pagination, la structure principale sera la même (total, page et items).

Qu'en penses tu @FBibonne  ?

2024-07-10 07:04 UTC, EmmanuelDemey requested changes

2024-07-10 07:04 UTC, EmmanuelDemey commented on src/main/java/fr/insee/rmes/persistance/sparql_queries/code_list/CodeListQueries.java
> +		return "SELECT ?labelLg1 ?labelLg2 \n"
Peux tu en profiter pour externaliser cette query dans un fichier ftlh ?

2024-07-10 13:01 UTC, FBibonne commented on src/main/java/fr/insee/rmes/bauhaus_services/code_list/CodeListServiceImpl.java
> -		result.put("items", items);
Le problème il me semble c'est que getCodesForCodeList ne doit pas renvoyer un String mais un objet Page<CodeList> avec un attribut page, un attribut total et un attribut items qui porte la liste des CodeLIst retournée. 

Mais j'ai l'impression qu'il y a une confusion entre la ressource et la représentation de la ressource renvoyée par le endpoint.

2024-07-10 13:04 UTC, FBibonne commented on src/main/java/fr/insee/rmes/persistance/sparql_queries/code_list/CodeListQueries.java
> +		return "SELECT ?labelLg1 ?labelLg2 \n"
Et d'écrire un test testscontainers sur la requête ;-)

2024-07-10 13:20 UTC, FBibonne requested changes
Pourquoi CodeListResponse ne s'appelle pas CodeLlist et CodeList DetailledCodeList

Il manque des changements dans les types retournés par plusieurs méthodes de controllers

2024-07-11 06:39 UTC, EmmanuelDemey commented on src/main/java/fr/insee/rmes/bauhaus_services/code_list/CodeListServiceImpl.java
> -		result.put("items", items);
nous sommes donc d'accord. On garde la propriété items. Mais nous devons retourner un objet de type Page par exemple.

2024-07-18 08:45 UTC, GtanSndil commented on src/main/java/fr/insee/rmes/webservice/codesLists/CodeListsResources.java
> +    public ResponseEntity<Object> getDetailedCodesListByNotation(@PathVariable("notation") String notation) throws RmesException {
la méthode getDetailedCodesListJson était utilisée pour les codeList et les PartialCodeList et renvoyait un Json. Comme le type d'objet devant désormais être retourné est différent, il était plus simple de faire une méthode pour les codeList et une autre pour les PartialCodeList.
Je propose que désormais : 
getDetailedCodesList renvoie un objet de type CodeListResponse.
getDetailedPartialCodesList renvoie un objet de type String (l'objet PartialCodeList n'existe pas pour l'instant. NB : on retournait jusque-là un Json dont le nom d'un des attributs est variable car il dépend de la valeur d'un autre attribut... donc cela fera l'objet d'une autre carte GitHub)

2024-07-18 10:30 UTC, GtanSndil commented on src/main/java/fr/insee/rmes/bauhaus_services/code_list/CodeListServiceImpl.java
> -		result.put("items", items);
Fait

2024-07-18 12:48 UTC, GtanSndil commented on src/main/java/fr/insee/rmes/persistance/sparql_queries/code_list/CodeListQueries.java
> +		return "SELECT ?labelLg1 ?labelLg2 \n"
j'ai externalisé la query. 
Pour le test container, je fais une carte à part.

2024-07-18 13:27 UTC, GtanSndil commented
Pourquoi CodeListResponse ne s'appelle pas CodeLlist et CodeList DetailledCodeList 
=> corrigé. Par contre je ne sais pas bien si les classes doivent rester là où elles sont : DetailedCodeList dans Bauhaus_service, CodeList dans config>swagger>model>code_list (mettre les 2 dans config>swagger>model>code_list ?)

Il manque des changements dans les types retournés par plusieurs méthodes de controllers
=> les méthodes publishFullCodeList  et getDetailedCodesListByNotation retournent désormais resp. ResponseEntity<String> et ResponseEntity<CodeList>. Est-ce que ça répond à ta remarque ?

2024-07-19 07:45 UTC, EmmanuelDemey approved these changes

2024-07-19 07:48 UTC, merged