684 complter la suppression dun jeu de donnes
InseeFr/Bauhaus-Back-Office pull request #705
Opened 2024-07-15 14:26 UTC by GtanSndil

delete the catalogRecord associated with the dataset
delete any alternative identifier associated with the dataset
delete any white nodes related to temporal coverage
delete any white nodes related to derivation
block deletion if a derived dataset exists

for tests in TestDatasetsResourcesEnvProd : two tests no longer passed: shouldDeleteADatasetIfDatasetContributorBasedOnStamp() and shouldDeleteADatasetIfDatasetContributorBasedOnStamp() Reason : RmesExceptionHandler    : null {"details":"Can't read query getDerivedDataset.ftlh","message":"The following has evaluated to null or missing:\n==> ID
it would be necessary to modify the @TestConfiguration, I tried but unsuccessfull => 
- added 
@MockBean
DatasetService datasetService;
- deleted @TestConfiguration and shouldNotDeleteNotUnpublishedDataset()
- considered that the test shouldNotDeleteNotUnpublishedDatasetAndReturn406() in DatasetServiceImpl is enough in a first instance to test a non unpublished dataset deletion (should not be deleted)

2024-07-19 08:08 UTC, EmmanuelDemey requested changes

2024-07-19 08:08 UTC, EmmanuelDemey commented on src/test/java/fr/insee/rmes/integration/authorizations/TestDatasetsResourcesEnvProd.java
> +//    static class DatasetServiceImplStub extends DatasetServiceImpl{
Pour pouvoir merger ceci, je préfère tout ce code pas nécéssaire

2024-07-19 10:02 UTC, GtanSndil commented on src/test/java/fr/insee/rmes/integration/authorizations/TestDatasetsResourcesEnvProd.java
> +//    static class DatasetServiceImplStub extends DatasetServiceImpl{
fait (j'avais gardé ça pour Fabrice mais il pourra revenir à la "classe" DatasetServiceImplStub qu'il avait créée en allant sur l'avant-dernier commit)

2024-07-22 13:53 UTC, JeromeMBourgeois approved these changes

2024-07-22 13:54 UTC, merged