feat: use ExceptionHandler for OperationsResources controller
InseeFr/Bauhaus-Back-Office pull request #766
Opened 2024-09-19 13:14 UTC by EmmanuelDemey

2024-09-23 10:11 UTC, FBibonne requested changes
Si on utilise l'exception handler, du coup, on peut affiner les types retournés( voir les commentaires)

Il faudrait aussi retirer la javadoc des méthodes dans OperationsResources car elle n'apporte rien

2024-09-23 10:11 UTC, FBibonne commented on src/main/java/fr/insee/rmes/webservice/operations/OperationsResources.java
>  	public ResponseEntity<Object> setOperationById(@PathVariable(Constants.ID) String id,
retourner ` ResponseEntity<Void>`

2024-09-23 10:11 UTC, FBibonne commented on src/main/java/fr/insee/rmes/webservice/operations/OperationsResources.java
>  	public ResponseEntity<Object> createOperation(
retourner ` ResponseEntity<String>`

2024-09-23 10:11 UTC, FBibonne commented on src/main/java/fr/insee/rmes/webservice/operations/OperationsResources.java
>  	public ResponseEntity<Object> setOperationValidation(@PathVariable(Constants.ID) String id) throws RmesException {
` ResponseEntity<String>`

2024-09-25 11:30 UTC, EmmanuelDemey commented on src/main/java/fr/insee/rmes/webservice/operations/OperationsResources.java
>  		if (accept != null && accept.equals(MediaType.APPLICATION_XML_VALUE)) {
@FBibonne pas sur de comprendre. Car dan un cas, nous souhaitons du JSONet de l'autre du XML.

2024-09-26 06:48 UTC, FBibonne commented on src/main/java/fr/insee/rmes/webservice/operations/OperationsResources.java
>  		if (accept != null && accept.equals(MediaType.APPLICATION_XML_VALUE)) {
operationsService.getOperationByID(id) renvoie un objet de type Operation. En disant à la méthode de renvoyer une ResponseEntity<Operation> on laisse spring s'occuper de la sérialisation. Il devra alors automatiquement sérialiser en xml on json selon le paramètre accept qui figurait dans la requête http

2024-09-26 09:19 UTC, FBibonne approved these changes

2024-09-26 15:11 UTC, merged