Change document and link id in request
InseeFr/Bauhaus-Back-Office pull request #815
Opened 2024-11-26 16:00 UTC by GtanSndil

use an object instead of directly a String
for 
PUT /documents/document/{id}
PUT /documents/link/{id}
DELETE /documents/document/{id}
DELETE /documents/link/{id}

2024-12-02 08:56 UTC, HugoBouttes commented on src/main/java/fr/insee/rmes/bauhaus_services/Constants.java
string sans majuscule ?

2024-12-02 10:43 UTC, GtanSndil commented on src/main/java/fr/insee/rmes/bauhaus_services/Constants.java
effectivement merci

2024-12-02 20:08 UTC, EmmanuelDemey requested changes

2024-12-02 20:08 UTC, EmmanuelDemey commented on src/main/java/fr/insee/rmes/bauhaus_services/Constants.java
> +	public static final String TYPE_STRING = "String";
Peux tu ajouter cette constant dans le bon block ? Je crois que c'est rangé par ordre alphabétique.

2024-12-04 09:23 UTC, HugoBouttes approved these changes

2024-12-04 09:24 UTC, merged